version: "2.4"

services:
  web:
    build: ./Website
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  autogrowpi:
    build: .
    command: python /src/AutoGrowPi.py
